image:
  file: .gitpod.Dockerfile

ports:
  - name: Main Dashboard
    port: 80
    onOpen: open-preview
    visibility: public
  - name: AnythingLLM
    port: 3001
    onOpen: ignore
    visibility: public
  - name: Kestra Workflows  
    port: 8080
    onOpen: ignore
    visibility: public
  - name: Ollama API
    port: 11434
    onOpen: ignore
    visibility: private
  - name: DocETL Service
    port: 5000
    onOpen: ignore
    visibility: public

tasks:
  - name: Setup Platform
    before: |
      echo "Preparing workspace..."
      mkdir -p {documents,organized,shared,processed,configs,workflows,static,jsoncrack}
    init: |
      echo "Setting up Document Intelligence Platform..."
      # Make scripts executable
      chmod +x setup.sh start.sh 2>/dev/null || echo "Scripts not found yet"
    command: |
      echo "🚀 Workspace ready!"
      echo "Run './start.sh' to launch the platform"
      echo "Or run individual commands step by step"

vscode:
  extensions:
    - ms-vscode.vscode-json
    - ms-python.python
    - redhat.vscode-yaml
