version: '3.8'

services:
  # Document Processing & AI
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm
    ports:
      - "3001:3001"
    volumes:
      - anythingllm_storage:/app/server/storage
      - anythingllm_vector_cache:/app/vector-cache
    environment:
      - STORAGE_DIR=/app/server/storage
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://ollama:11434
      - JWT_SECRET=gitpod-secret-key-change-this
    depends_on:
      - ollama
    restart: unless-stopped

  # Workflow Orchestration
  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    ports:
      - "8080:8080"
    volumes:
      - kestra_data:/app/storage
      - kestra_logs:/app/logs
      - ./workflows:/app/workflows
    environment:
      - KESTRA_CONFIGURATION_PATH=/app/application.yml
    restart: unless-stopped

  # File Organization & Management
  file-organizer:
    build:
      context: .
      dockerfile: Dockerfile.organizer
    container_name: file-organizer
    ports:
      - "3002:3000"
    volumes:
      - ./documents:/app/documents
      - ./organized:/app/organized
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Document ETL Processing
  docetl:
    build:
      context: .
      dockerfile: Dockerfile.docetl
    container_name: docetl
    ports:
      - "5000:5000"
    volumes:
      - ./documents:/app/input
      - ./processed:/app/output
      - ./configs:/app/configs
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  # JSON Visualization (simplified for Gitpod)
  jsoncrack:
    image: nginx:alpine
    container_name: jsoncrack
    ports:
      - "8000:80"
    volumes:
      - ./jsoncrack:/usr/share/nginx/html
    restart: unless-stopped

  # Reverse Proxy & UI
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    depends_on:
      - anythingllm
      - kestra
      - docetl
    restart: unless-stopped

  # Database for workflows and metadata
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=document_intel
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=gitpod-postgres-pass
    restart: unless-stopped

  # Redis for caching and job queues
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  ollama_data:
  anythingllm_storage:
  anythingllm_vector_cache:
  kestra_data:
  kestra_logs:
  postgres_data:
  redis_data:
